### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/graphicalweb-keynote#1]
Hi @cjgammon!
Me again 👋 . Same deal: I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project?

Thanks for any info.

-Fil

**Comment by cjgammon** [comment]
we can archive this.

**Comment by filmaj** [comment]
Cool, updated the readme to reflect that. Will archive shortly.
